### ISSUE TITLE
TOC(Table of Contents)가 제대로 작동하지 않습니다.

### ISSUE THREAD

**Issue by mmcrs** [tistory-project/hELLO#33]
- 운영체제: Windows 10 19042.1052
- 브라우저: Firefox (베타)
- 버전: 90.0b6
- 스킨 버전: 3.4.0

![Animation1](https://user-images.githubusercontent.com/85152618/121762968-d75ff600-cb73-11eb-9736-163c3dfe52e1.gif)

녹화 링크: https://mmcrs.in/391

이렇게 테이블 누르면 그 테이블이 있는 위치로 이동해야하는데 스킨 업데이트하고나서 제대로 작동이 되지 않습니다.
무슨 코드를 잘못 건드린걸까요?

**Comment by pronist** [comment]
@mmcrs 스킨 버전 3.4.2 버전으로 다시 적용시켜 보시겠어요? 그 부분은 3.4.0 에서 발생하는 버그인 것은 맞습니다.

**Comment by mmcrs** [comment]
버전 올리니 해결됐습니다. 감사합니다.
